name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: 
  mdi:
  pushable_button:
  gap: ^3.0.1
  sign_in_button: ^3.2.0
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  awesome_snackbar_content: ^0.1.3
  intl: ^0.19.0
  dropdown_button2: ^2.3.8
  awesome_dialog: ^3.2.1
  image_picker: ^0.8.6
  firebase_storage: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
